export const FETCH_PROFILE_START = "FETCH_PROFILE_START";
export const FETCH_PROFILE_SUCCESS = "FETCH_PROFILE_SUCCESS";
export const FETCH_PROFILE_FAIL = "FETCH_PROFILE_FAIL";

export const FETCH_TIMELINE_START = "FETCH_TIMELINE_START";
export const FETCH_TIMELINE_SUCCESS = "FETCH_TIMELINE_SUCCESS";
export const FETCH_TIMELINE_FAIL = "FETCH_TIMELINE_FAIL";

export const POST_CONTENT_START = "POST_CONTENT_START";
export const POST_CONTENT_SUCCESS = "POST_CONTENT_SUCCESS";
export const POST_CONTENT_FAIL = "POST_CONTENT_FAIL";

export const POST_MEDIA_START = "POST_MEDIA_START";
export const POST_MEDIA_SUCCESS = "POST_MEDIA_SUCCESS";
export const POST_MEDIA_FAIL = "POST_MEDIA_FAIL";

export const FETCH_NOTIFICATIONS_START = "FETCH_NOTIFICATIONS_START";
export const FETCH_NOTIFICATIONS_SUCCESS = "FETCH_NOTIFICATIONS_SUCCESS";
export const FETCH_NOTIFICATIONS_FAIL = "FETCH_NOTIFICATIONS_FAIL";

export const POST_TWEET_START = "POST_TWEET_START";
export const POST_TWEET_SUCCESS = "POST_TWEET_SUCCESS";
export const POST_TWEET_FAIL = "POST_TWEET_FAIL";

export const GET_POST_START = "GET_POST_START";
export const GET_POST_SUCCESS = "GET_POST_SUCCESS";
export const GET_POST_FAIL = "GET_POST_FAIL";

export const FETCH_FOLLOWERS_START = "FETCH_FOLLOWERS_START";
export const FETCH_FOLLOWERS_SUCCESS = "FETCH_FOLLOWERS_SUCCESS";
export const FETCH_FOLLOWERS_FAIL = "FETCH_FOLLOWERS_FAIL";

export const FETCH_FOLLOWING_START = "FETCH_FOLLOWING_START";
export const FETCH_FOLLOWING_SUCCESS = "FETCH_FOLLOWING_SUCCESS";
export const FETCH_FOLLOWING_FAIL = "FETCH_FOLLOWING_FAIL";

export const POST_FOLLOWSOMEONE_START = "POST_FOLLOWSOMEONE_START";
export const POST_FOLLOWSOMEONE_SUCCESS = "POST_FOLLOWSOMEONE_SUCCESS";
export const POST_FOLLOWSOMEONE_FAIL = "POST_FOLLOWSOMEONE_FAIL";

export const POST_UNFOLLOWSOMEONE_START = "POST_UNFOLLOWSOMEONE_START";
export const POST_UNFOLLOWSOMEONE_SUCCESS = "POST_UNFOLLOWSOMEONE_SUCCESS";
export const POST_UNFOLLOWSOMEONE_FAIL = "POST_UNFOLLOWSOMEONE_FAIL";

export const PUT_EDITPROFILE_START = "PUT_EDITPROFILE_START";
export const PUT_EDITPROFILE_SUCCESS = "PUT_EDITPROFILE_SUCCESS";
export const PUT_EDITPROFILE_FAIL = "PUT_EDITPROFILE_FAIL";

export const PATCH_THEME_START = "PATCH_THEME_START";
export const PATCH_THEME_SUCCESS = "PATCH_THEME_SUCCESS";
export const PATCH_THEME_FAIL = "PATCH_THEME_FAIL";

export const PATCH_PICTURE_START = "PATCH_PICTURE_START";
export const PATCH_PICTURE_SUCCESS = "PATCH_PICTURE_SUCCESS";
export const PATCH_PICTURE_FAIL = "PATCH_PICTURE_FAIL";

export const SEARCH_BAR_START = "SEARCH_BAR_START";
export const SEARCH_BAR_FAIL = "SEARCH_BAR_FAIL";
export const SEARCH_BAR_SUCCESS = "SEARCH_BAR_SUCCESS";

export const GET_MEDIA_START = "GET_MEDIA_START";
export const GET_MEDIA_SUCCESS = "GET_MEDIA_SUCCESS";
export const GET_MEDIA_FAIL = "GET_MEDIA_FAIL";

export const POST_REACTION_START = "POST_REACTION_START";
export const POST_REACTION_SUCCESS = "POST_REACTION_SUCCESS";
export const POST_REACTION_FAIL = "POST_REACTION_FAIL";

export const DELETE_REACTION_START = "DELETE_REACTION_START";
export const DELETE_REACTION_SUCCESS = "DELETE_REACTION_SUCCESS";
export const DELETE_REACTION_FAIL = "DELETE_REACTION_FAIL";

export const RESET_PROFILE = "RESET_PROFILE";
