export const FETCH_PROFILE_START = "FETCH_PROFILE_START";
export const FETCH_PROFILE_SUCCESS = "FETCH_PROFILE_SUCCESS";
export const FETCH_PROFILE_FAIL = "FETCH_PROFILE_FAIL";

export const FETCH_TIMELINE_START = "FETCH_TIMELINE_START";
export const FETCH_TIMELINE_SUCCESS = "FETCH_TIMELINE_SUCCESS";
export const FETCH_TIMELINE_FAIL = "FETCH_TIMELINE_FAIL";

export const POST_TWEET_START = "POST_TWEET_START";
export const POST_TWEET_SUCCESS = "POST_TWEET_SUCCESS";
export const POST_TWEET_FAIL = "POST_TWEET_FAIL";

export const FETCH_FOLLOWERS_START = "FETCH_FOLLOWERS_START";
export const FETCH_FOLLOWERS_SUCCESS = "FETCH_FOLLOWERS_SUCCESS";
export const FETCH_FOLLOWERS_FAIL = "FETCH_FOLLOWERS_FAIL";

export const SEARCH_BAR_START = "SEARCH_BAR_START";
export const SEARCH_BAR_FAIL = "SEARCH_BAR_FAIL";
export const SEARCH_BAR_SUCCESS = "SEARCH_BAR_SUCCESS";
